server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:stc
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 6729688848964c
    password: 4de445845769c7
    protocol: smtp
    smtp:
      auth: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 10
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 2000
        retryExceptions:
          - java.io.IOException
  rateLimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1000
        timeoutDuration: 500
logging:
  level:
    root: INFO  # Root logging level
    com.backend.stc: DEBUG  # Set specific level for your package
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
